import { useRouter } from "next/router";
import Layout from '@/components/layout';
import Link from "next/link";
import styles from '../../../styles/ItemList.module.css';

export const metadata = {
    title: "AI 꽃 도감",
    description: "Generated by Kim ji hyeok",
  };

const Post = () => {
    const router = useRouter();
    const { famlNm, imgUrl, krnm, fturCn } = router.query;

    function getData() {}

    return (
        <Layout>
            <div className="my-24 mx-16 flex flex-col items-start ">
                <Link href="../info">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    height="24px"
                    viewBox="0 -960 960 960"
                    width="24px"
                    className="mb-3 ml-3"
                    fill="#5f6368"
                >
                    <path d="M407.65-72.35 0-480l407.65-407.65L486.3-809l-329 329 329 329-78.65 78.65Z"
                    />
                </svg>
                </Link>
                <h1 className={styles.index}>{krnm} </h1>
                <h1 className="mb-6 mx-5 text-lg font-bold text-rose-400">{famlNm} </h1>
                <img className="mx-4 my-3" src={imgUrl} alt={krnm} />
                <h1 className="mt-4 mb-6 mx-2 text-lg font-bold">{fturCn} </h1>
            </div>
        </Layout>
    )
};

export default Post;