import { useRouter } from 'next/router'
import Layout from '@/components/layout'
import Link from 'next/link'
import styles from '../../../styles/ItemList.module.css'
import Image from 'next/image'
import { PlantIndexItem } from '@/types/type'
import PreviousPage from '@/pages/assets/icons/PreviousPage.svg'

export const metadata = {
  title: 'AI 꽃 도감',
  description: 'Generated by Kim ji hyeok',
}

const Post = () => {
  const router = useRouter()
  const { famlNm, imgUrl, krnm, fturCn } = router.query as PlantIndexItem

  return (
    <Layout>
      <div className="my-24 mx-16 flex flex-col items-start ">
        <Link href="../info" aria-label="식물 도감 페이지로 이동">
          <PreviousPage
            className="mb-3 ml-3 h-12"
            width="24px"
            height="24px"
            fill="#5f6368"
          />
        </Link>
        <div className="ml-4">
          <h2 className={styles.index}>{krnm} </h2>
          <h3 className="mb-6 mx-2 text-lg font-bold text-rose-400">
            {famlNm}
          </h3>
        </div>
        <Image
          className="mx-4 my-3"
          src={imgUrl}
          alt={krnm}
          width={500}
          height={300}
        />
        <p className="mt-4 mb-6 mx-2 text-lg font-bold">{fturCn}</p>
      </div>
    </Layout>
  )
}

export default Post
