import { useRouter } from 'next/router'
import Layout from '@/components/layout'
import Link from 'next/link'
import styles from '../../../styles/ItemList.module.css'
import Image from 'next/image'
import { plantIndexFetchData } from '@/hooks/plantIndexFetchData'
import { PlantIndexItem } from '@/types/type'
import PreviousPage from '@/pages/assets/icons/PreviousPage.svg'
import { useEffect, useState } from 'react'

export const metadata = {
  title: 'AI 꽃 도감',
  description: 'Generated by Kim ji hyeok',
}

const Post = () => {
  const [plantData, setPlantData] = useState<PlantIndexItem | null>(null)
  const router = useRouter()
  const { krnm } = router.query
  const { data, isLoading } = plantIndexFetchData()

  useEffect(() => {
    if (!data || isLoading || !krnm) return
    const decodedKrnm = decodeURIComponent(krnm as string)

    const foundPlant = data.response.body.items.item.find(
      (p: PlantIndexItem) => p.krnm === decodedKrnm
    )

    setPlantData(foundPlant || null)
  }, [data, isLoading, krnm])

  if (isLoading) return
  return (
    <Layout>
      <div className="my-24 mx-16 flex flex-col items-start ">
        <Link href="../info" aria-label="식물 도감 페이지로 이동">
          <PreviousPage className="mb-3 ml-3 w-6 h-6" fill="#5f6368" />
        </Link>
        {plantData && (
          <>
            <div className="ml-4">
              <h2 className={styles.index}>{plantData?.krnm} </h2>
              <h3 className="mb-6 mx-2 text-lg font-bold text-rose-400">
                {plantData?.famlNm}
              </h3>
            </div>
            <Image
              className="mx-4 my-3"
              src={plantData?.imgUrl}
              alt={plantData?.krnm}
              width={500}
              height={300}
            />
            <p className="mt-4 mb-6 mx-2 text-lg font-bold">
              {plantData?.fturCn}
            </p>
          </>
        )}
      </div>
    </Layout>
  )
}

export default Post
