import { useRouter } from 'next/router'
import Layout from '@/components/common/Layout'
import Link from 'next/link'
import Image from 'next/image'
import { plantIndexFetchData } from '@/hooks/plantIndexFetchData'
import { PlantIndexItem } from '@/types/type'
import Unliked from '@/pages/assets/icons/Unliked.svg'
import Liked from '@/pages/assets/icons/Liked.svg'
import Share from '@/pages/assets/icons/Share.svg'
import PreviousPage from '@/pages/assets/icons/PreviousPage.svg'
import { useEffect, useState } from 'react'
import { useAuth } from '@/context/AuthContext'
import { useCapturedPlantImageStore } from '@/store/imageStore'
import LoginRequiredModal from '@/components/modal/LoginRequiredModal'
import SearchFeedbackToast from '@/components/common/SearchFeedbackToast'

export const metadata = {
  title: 'AI 꽃 도감',
  description: 'Generated by Kim ji hyeok',
}

const Post = () => {
  const [plantData, setPlantData] = useState<PlantIndexItem | null>(null)
  const { loginUser } = useAuth()
  const [likedPlants, setLikedPlants] = useState<string[]>([])
  const [CopyTooltipIndex, ShowCopyTooltipIndex] = useState('')
  const [openLoginRequiredModal, setOpenLoginRequiredModal] = useState(false)
  const [openSearchFeedbackToast, setOpenSearchFeedbackToast] = useState(false)
  const { imageUrl, setImageUrl } = useCapturedPlantImageStore()
  const router = useRouter()
  const { prevPage, sort } = router.query
  const { krnm } = router.query
  const { data, isLoading } = plantIndexFetchData(1, 300)

  useEffect(() => {
    if (!data || isLoading || !krnm) return
    const decodedKrnm = decodeURIComponent(krnm as string)

    const foundPlant = data?.indexList.find(
      (p: PlantIndexItem) => p.krnm === decodedKrnm
    )

    setPlantData(foundPlant || null)
  }, [data, isLoading, krnm])

  useEffect(() => {
    if (loginUser) {
      setLikedPlants(
        JSON.parse(localStorage.getItem(`${loginUser}.likedPlants`) || '[]')
      )
    }
  }, [loginUser])

  useEffect(() => {
    if (imageUrl) {
      setOpenSearchFeedbackToast(true)
    }
  }, [])

  useEffect(() => {
    if (
      prevPage === 'ai-flower-detection' &&
      sessionStorage.getItem('cameFromAiFlowerDetection') === 'true'
    ) {
      const storedPlants = JSON.parse(
        localStorage.getItem(`${loginUser}.findPlants`) || '[]'
      )

      if (!storedPlants.includes(krnm)) {
        localStorage.setItem(
          `${loginUser}.findPlants`,
          JSON.stringify([...storedPlants, krnm])
        )
      }
      sessionStorage.removeItem('cameFromAiFlowerDetection')
    }
  }, [prevPage, loginUser, krnm])

  useEffect(() => {
    const handleRouteChange = () => {
      setImageUrl('')
    }

    router.events.on('routeChangeStart', handleRouteChange)

    return () => {
      router.events.off('routeChangeStart', handleRouteChange)
    }
  }, [router, setImageUrl])

  const handlePlantLike = () => {
    if (typeof krnm === 'string' && loginUser) {
      if (likedPlants.includes(krnm)) {
        setLikedPlants((prev) => {
          const updatedLikedPlants = prev.filter((id: string) => id !== krnm)
          localStorage.setItem(
            `${loginUser}.likedPlants`,
            JSON.stringify(updatedLikedPlants)
          )
          return updatedLikedPlants
        })
      } else {
        setLikedPlants((prev) => {
          const updatedLikedPlants = [...prev, krnm]
          localStorage.setItem(
            `${loginUser}.likedPlants`,
            JSON.stringify(updatedLikedPlants)
          )
          return updatedLikedPlants
        })
      }
    } else {
      setOpenLoginRequiredModal(true)
    }
  }

  const handlePlantLinkShare = () => {
    try {
      if (typeof krnm === 'string') {
        const baseUrl = process.env.NEXT_PUBLIC_BASE_URL
        navigator.clipboard.writeText(`${baseUrl}/view/${krnm}`)
        ShowCopyTooltipIndex(krnm)
        setTimeout(() => {
          ShowCopyTooltipIndex('')
        }, 1000)
      }
    } catch (err) {
      console.error('링크 복사 실패', err)
    }
  }
  if (isLoading) return
  return (
    <Layout>
      <div className="flex min-h-screen w-full flex-col items-center bg-[#FEF5CC] sm:px-2 xl:px-8 2xl:px-16 min-[1920px]:px-[32rem]">
        {plantData && (
          <>
            <div className="relative flex w-full flex-col items-center gap-5">
              <div className="relative mt-20 flex flex-col items-center">
                <Link
                  href={{
                    pathname:
                      prevPage && prevPage !== 'home' ? `/${prevPage}` : '/',
                    ...(sort ? { query: { sort } } : {}),
                  }}
                  aria-label="식물 도감 페이지로 이동"
                  className="absolute left-[-80px] top-8 flex items-center justify-center rounded-2xl border bg-white p-2"
                  passHref
                >
                  <PreviousPage
                    className="h-6 w-6"
                    fill="#5f6368"
                    aria-hidden="true"
                  />
                </Link>
                <h1 className="my-4 text-5xl font-bold text-[#797D48]">
                  {plantData?.krnm}
                </h1>
                <h2 className="my-1 text-3xl text-[#797D48]">
                  {plantData?.famlNm} / {plantData?.kornFamlNm}
                </h2>
              </div>
              <div className="flex w-full flex-row items-end justify-end">
                <div className="relative mr-16 mt-4 flex flex-row justify-end gap-4">
                  <button
                    type="button"
                    aria-label={
                      likedPlants.includes(plantData?.krnm)
                        ? '좋아요 해제'
                        : '좋아요 추가'
                    }
                    onClick={(e) => {
                      e.preventDefault()
                      handlePlantLike()
                    }}
                    className="p-1"
                  >
                    {typeof krnm === 'string' && likedPlants.includes(krnm) ? (
                      <Liked
                        className="h-8 w-8"
                        fill="#FF5C8D"
                        aria-hidden="true"
                      />
                    ) : (
                      <Unliked className="h-8 w-8" aria-hidden="true" />
                    )}
                  </button>
                  <button
                    type="button"
                    aria-label="이 식물 페이지를 공유"
                    onClick={(e) => {
                      e.preventDefault()
                      handlePlantLinkShare()
                    }}
                    className="relative p-1"
                  >
                    <Share className="h-8 w-8" aria-hidden="true" />
                    {CopyTooltipIndex === krnm && (
                      <div className="absolute left-1/2 top-full mb-2 -translate-x-1/2 transform whitespace-nowrap rounded bg-black px-3 py-1 text-sm text-white transition-opacity duration-300">
                        링크가 복사되었습니다!
                      </div>
                    )}
                  </button>
                </div>
              </div>
            </div>
            <hr className="my-6 mb-10 w-full" />
            <figure className="flex w-full flex-row">
              <Image
                className="mx-16 my-12 w-1/2 rounded-xl border"
                src={plantData?.imgUrl}
                alt={`${plantData?.krnm}식물`}
                width={400}
                height={300}
              />
              <figcaption className="w-1/2 self-center justify-self-center px-8 text-[#797D48]">
                <dl>
                  <div className="my-4 text-3xl font-semibold">
                    <dt className="inline-block">색상:</dt>
                    <dd className="ml-2 inline-block">
                      {plantData?.flwrClorCn}
                    </dd>
                  </div>
                  <div className="my-4 text-3xl font-semibold">
                    <dt className="inline-block">개화시기:</dt>
                    <dd className="ml-2 inline-block">
                      {plantData?.bloomPeriodCn}
                    </dd>
                  </div>
                  <div className="my-4 font-semibold">
                    <dt className="inline-block text-3xl">특징:</dt>
                    <dd className="inline-block text-xl">
                      {plantData?.fturCn}
                    </dd>
                  </div>
                </dl>
              </figcaption>
            </figure>
          </>
        )}
        {imageUrl && (
          <SearchFeedbackToast
            openToast={openSearchFeedbackToast}
            onClick={() => setOpenSearchFeedbackToast(true)}
            onClose={() => setOpenSearchFeedbackToast(false)}
            imageUrl={imageUrl}
          />
        )}
      </div>
      {openLoginRequiredModal && (
        <LoginRequiredModal
          onClose={() => setOpenLoginRequiredModal(false)}
          bgOverlay={false}
          onSecondButtonClick={() => router.push('/login')}
        />
      )}
    </Layout>
  )
}

export default Post
