declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_CHATGPT_API_KEY: string
    NEXT_PUBLIC_CHATGPT_API_URL: string
    NEXT_PUBLIC_TEACHABLE_MACHINE_MODEL_API_URL: string
    NEXT_PUBLIC_TEACHABLE_MACHINE_METADATA_API_URL: string
    NEXT_PUBLIC_GARDEN_API_KEY: string
    NEXT_PUBLIC_GARDEN_API_PATH: string
    NEXT_PUBLIC_GARDEN_API_URL: string
  }
}
